### ISSUE TITLE
Error in spdb.save

### ISSUE THREAD

**Issue by zy-fang** [Avon0905/SPDB_API#1]
Hi, 
Thank you for building the single-cell protein database. However, when I tried to download and save the data using spdb.save, I encountered the following error. Do you know what might be the reason for this?

Checking if files are all available...
Error in `setdiff()` at spdb_api.R:40:8:
! `x` and `y` are not compatible.
`y` must be a data frame.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by Avon0905** [comment]
Hi,

Thank you for trying our single-cell proteomic database and pointing out this issue. We have fixed this bug caused by _data type_ in the updated spdb_api.R. Please clone the latest spdb_api and try this function again.

Best,
Fang

**Comment by zy-fang** [comment]
Thank you. I can download the datasets now.

Best,
Zhaoyu
